apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: sjpexzlvn-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/jsmid/rhtap-qe:d55741bde6b2cee3a7c2e3216f1a1b6a66822704@sha256:5d0965ea221d1412944adceca1e991bd9e85c85ccd179ae8a04288c37b542653
          name: container-image
